version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.user # или admin
    environment:
      - DATABASE_URL=sqlite:///./knives.db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:latest
